### ISSUE TITLE
Feature suggestion: Allow fixing problems with regex replace

### ISSUE THREAD

**Issue by douira** [gmullerb/eslint-plugin-regex#6]
It would be nice if this rule could be made fixable by specifying a string that the original regex match is replaced with in order to fix the problem reported by a pattern.

Here's an example of a pattern that removes spaces after comments (a case where ESLint's spaced-comment rule isn't sufficient):
```json
{
  "plugins": [
    "regex"
  ],
  "rules": {
    "regex/invalid": [
      "error", [{
          "regex": "//\\s(\\S)",
          "fix": "//$1",
          "message": "errorMessage1",
      }]
    ]
  }
}
```

This plugin is already working great! I'm currently replacing with my IDE manually. If that could be integrated into this plugin that would make the workflow even more elegant.

**Comment by gmullerb** [comment]
**Thanks for proposing improvements!!**
I considered adding replacements at some point. It's Great Idea adding Capturing groups.
I think, I will add this improvement in two steps, first the replacement, then replacement with Capturing groups (**Great Idea! :+1: Thanks!!!**).
**Glad that you find this plugin so useful!**

**Comment by douira** [comment]
One idea would be to use [`String.prototype.replace`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_string_as_a_parameter) (or another RegEx standard replace function in the JavaScript core) to do capture group replacement automatically.

**Comment by gmullerb** [comment]
First phase, direct replacement done. :heavy_check_mark:

**Comment by gmullerb** [comment]
I added a **new feature** :bulb: :tada: :smile:, [Replacements with Functions for Invalid Patterns](https://github.com/gmullerb/eslint-plugin-regex#definition-of-the-function-used-to-replace-the-invalid-found-pattern).
This new feature will allow you to solve your issue. Although, I won't close this issue yet, because I will improve this new feature in order to make it even easier. (I advice you to wait for this improvement, but you can work from here)

**Comment by gmullerb** [comment]
I added an improvement feature :tada: :smile:, [Replacements with Functions for Invalid Patterns using Capturing Groups ](https://github.com/gmullerb/eslint-plugin-regex#definition-of-the-function-used-to-replace-the-invalid-found-pattern).
This improvement will allow you to solve your issue. 
```json
{
  "regex": "//\\s(\\S)",
  "replacement": {
    "function": "return captured[0]"
  }
}
```
Although, I won't close this issue yet, because I will add a new feature in order to make it even simpler.

**Comment by douira** [comment]
Even though this is not standard regex replace syntax it does solve the problem, so that's just as good! Thanks for your effort working on this issue. As you said, you can close the issue when you see fit.

**Comment by gmullerb** [comment]
With new features :tada: :fireworks: , you can have a smaller definition:

```json
{
  "regex": "//\\s(\\S)",
  "replacement": {
    "function": "$[0]"
  }
}
```

**Thanks Again!** :smile: :+1: 
(more new features to come)

**Comment by charles-allen** [comment]
@gmullerb - I struggled to create a replacement function that included `\n`. I wonder if I need to escape it somehow?

```js
{
  regex: '^import mapboxgl, ({[^}]*}) from \'mapbox-gl\'$',
  message: 'Import the initialized mapboxgl object from \'~/maps\'',
  replacement: { function: 'return "import { mapboxgl } from \'~/maps\'\n import " + captured[0] + " from \'mapbox-gl\'"' }
}
```

I bypassed the issue by using a semi-colon, and letting me formatting replace that with a line-break:

```js
{
  regex: '^import mapboxgl, ({[^}]*}) from \'mapbox-gl\'$',
  message: 'Import the initialized mapboxgl object from \'~/maps\'',
  replacement: { function: 'return "import { mapboxgl } from \'~/maps\'; import " + captured[0] + " from \'mapbox-gl\'"' }
}
```

```ts
// Before:
import mapboxgl, { GeoJSONSource } from 'mapbox-gl'

// After:
import { mapboxgl } from '~/maps'
import { GeoJSONSource } from 'mapbox-gl'
```
